// English → Russian team name translations
const TEAM_NAMES_RU = {
  // England — Premier League
  'Arsenal': 'Арсенал',
  'Chelsea': 'Челси',
  'Liverpool': 'Ливерпуль',
  'Manchester City': 'Манчестер Сити',
  'Manchester United': 'Манчестер Юнайтед',
  'Tottenham': 'Тоттенхэм',
  'Tottenham Hotspur': 'Тоттенхэм',
  'Newcastle': 'Ньюкасл',
  'Newcastle United': 'Ньюкасл',
  'Aston Villa': 'Астон Вилла',
  'West Ham': 'Вест Хэм',
  'West Ham United': 'Вест Хэм',
  'Brighton': 'Брайтон',
  'Brighton & Hove Albion': 'Брайтон',
  'Brentford': 'Брентфорд',
  'Fulham': 'Фулхэм',
  'Crystal Palace': 'Кристал Пэлас',
  'Everton': 'Эвертон',
  'Wolverhampton': 'Вулверхэмптон',
  'Wolverhampton Wanderers': 'Вулверхэмптон',
  'Nottingham Forest': 'Ноттингем Форест',
  'Nottm Forest': 'Ноттингем Форест',
  'Leicester': 'Лестер',
  'Leicester City': 'Лестер',
  'Southampton': 'Саутгемптон',
  'Ipswich': 'Ипсвич',
  'Ipswich Town': 'Ипсвич',
  'Bournemouth': 'Борнмут',
  'AFC Bournemouth': 'Борнмут',
  'Leeds': 'Лидс',
  'Leeds United': 'Лидс',
  'Burnley': 'Бёрнли',
  'Sheffield United': 'Шеффилд Юнайтед',
  'Luton': 'Лутон',
  'Luton Town': 'Лутон',
  'Sunderland': 'Сандерленд',
  'Middlesbrough': 'Мидлсбро',
  'Coventry': 'Ковентри',
  'Coventry City': 'Ковентри',
  'Stoke City': 'Сток Сити',
  'Watford': 'Уотфорд',
  'Queens Park Rangers': 'КПР',
  'Derby County': 'Дерби',
  'Millwall': 'Милуолл',
  'Norwich City': 'Норвич',
  'Preston': 'Престон',
  'Preston North End': 'Престон',
  'Swansea City': 'Суонси',
  'Cardiff City': 'Кардифф',
  'Hull City': 'Халл Сити',
  'Plymouth': 'Плимут',
  'Plymouth Argyle': 'Плимут',
  'Oxford United': 'Оксфорд',
  'Blackburn': 'Блэкберн',
  'Blackburn Rovers': 'Блэкберн',

  // Spain — La Liga
  'Real Madrid': 'Реал Мадрид',
  'Barcelona': 'Барселона',
  'Atletico Madrid': 'Атлетико Мадрид',
  'Atlético Madrid': 'Атлетико Мадрид',
  'Sevilla': 'Севилья',
  'Valencia': 'Валенсия',
  'Villarreal': 'Вильярреал',
  'Real Sociedad': 'Реал Сосьедад',
  'Athletic Bilbao': 'Атлетик Бильбао',
  'Athletic Club': 'Атлетик Бильбао',
  'Betis': 'Бетис',
  'Real Betis': 'Бетис',
  'Osasuna': 'Осасуна',
  'Girona': 'Жирона',
  'Mallorca': 'Мальорка',
  'Las Palmas': 'Лас-Пальмас',
  'Rayo Vallecano': 'Райо Вальекано',
  'Getafe': 'Хетафе',
  'Celta Vigo': 'Сельта',
  'Celta de Vigo': 'Сельта',
  'Alaves': 'Алавес',
  'Deportivo Alavés': 'Алавес',
  'Espanol': 'Эспаньол',
  'Espanyol': 'Эспаньол',
  'Valladolid': 'Вальядолид',
  'Real Valladolid': 'Вальядолид',
  'Leganes': 'Леганес',
  'CD Leganes': 'Леганес',

  // Germany — Bundesliga
  'Bayern Munich': 'Бавария',
  'Bayern München': 'Бавария',
  'Borussia Dortmund': 'Боруссия Дортмунд',
  'Bayer Leverkusen': 'Байер Леверкузен',
  'RB Leipzig': 'РБ Лейпциг',
  'Eintracht Frankfurt': 'Айнтрахт Франкфурт',
  'VfL Wolfsburg': 'Вольфсбург',
  'Wolfsburg': 'Вольфсбург',
  'Borussia Monchengladbach': 'Боруссия Мёнхенгладбах',
  'Borussia Mönchengladbach': 'Боруссия Мёнхенгладбах',
  'Union Berlin': 'Унион Берлин',
  '1. FC Union Berlin': 'Унион Берлин',
  'Freiburg': 'Фрайбург',
  'SC Freiburg': 'Фрайбург',
  'Hoffenheim': 'Хоффенхайм',
  'TSG Hoffenheim': 'Хоффенхайм',
  'Mainz': 'Майнц',
  'FSV Mainz 05': 'Майнц',
  '1. FSV Mainz 05': 'Майнц',
  'Werder Bremen': 'Вердер',
  'Augsburg': 'Аугсбург',
  'FC Augsburg': 'Аугсбург',
  'Stuttgart': 'Штутгарт',
  'VfB Stuttgart': 'Штутгарт',
  'Koln': 'Кёльн',
  'Cologne': 'Кёльн',
  '1. FC Köln': 'Кёльн',
  'Hertha Berlin': 'Герта',
  'Hertha BSC': 'Герта',
  'Hamburger SV': 'Гамбург',
  'Hamburg': 'Гамбург',
  'Heidenheim': 'Хайденхайм',
  '1. FC Heidenheim': 'Хайденхайм',
  'Bochum': 'Бохум',
  'VfL Bochum': 'Бохум',
  'Darmstadt': 'Дармштадт',
  'SV Darmstadt 98': 'Дармштадт',
  'Schalke': 'Шальке',
  'FC Schalke 04': 'Шальке',
  'Holstein Kiel': 'Кёльн',
  'St. Pauli': 'Санкт Паули',
  'FC St. Pauli': 'Санкт Паули',

  // Italy — Serie A
  'Juventus': 'Ювентус',
  'Inter': 'Интер',
  'Inter Milan': 'Интер',
  'AC Milan': 'Милан',
  'Milan': 'Милан',
  'Napoli': 'Наполи',
  'Roma': 'Рома',
  'AS Roma': 'Рома',
  'Lazio': 'Лацио',
  'SS Lazio': 'Лацио',
  'Atalanta': 'Аталанта',
  'Fiorentina': 'Фиорентина',
  'ACF Fiorentina': 'Фиорентина',
  'Torino': 'Торино',
  'FC Torino': 'Торино',
  'Bologna': 'Болонья',
  'Udinese': 'Удинезе',
  'Sassuolo': 'Сасуоло',
  'US Sassuolo': 'Сасуоло',
  'Sampdoria': 'Сампдория',
  'UC Sampdoria': 'Сампдория',
  'Cagliari': 'Кальяри',
  'Hellas Verona': 'Верона',
  'Verona': 'Верона',
  'Spezia': 'Специя',
  'Empoli': 'Эмполи',
  'Lecce': 'Лечче',
  'US Lecce': 'Лечче',
  'Monza': 'Монца',
  'AC Monza': 'Монца',
  'Venezia': 'Венеция',
  'Genoa': 'Дженоа',
  'Frosinone': 'Фрозиноне',
  'Como': 'Комо',
  'Como 1907': 'Комо',
  'Parma': 'Парма',

  // France — Ligue 1
  'Paris Saint-Germain': 'ПСЖ',
  'PSG': 'ПСЖ',
  'Marseille': 'Марсель',
  'Olympique Marseille': 'Марсель',
  'Lyon': 'Лион',
  'Olympique Lyonnais': 'Лион',
  'Monaco': 'Монако',
  'AS Monaco': 'Монако',
  'Lille': 'Лилль',
  'LOSC Lille': 'Лилль',
  'Nice': 'Ницца',
  'OGC Nice': 'Ницца',
  'Rennes': 'Ренн',
  'Stade Rennais': 'Ренн',
  'Lens': 'Ланс',
  'RC Lens': 'Ланс',
  'Strasbourg': 'Страсбур',
  'Montpellier': 'Монпелье',
  'Nantes': 'Нант',
  'Brest': 'Брест',
  'Stade Brestois': 'Брест',
  'Reims': 'Реймс',
  'Stade de Reims': 'Реймс',
  'Toulouse': 'Тулуза',
  'Metz': 'Мец',
  'FC Metz': 'Мец',
  'Le Havre': 'Гавр',
  'Auxerre': 'Осер',
  'AJ Auxerre': 'Осер',
  'Angers': 'Анже',
  'Saint-Etienne': 'Сент-Этьен',
  'AS Saint-Etienne': 'Сент-Этьен',

  // Netherlands
  'Ajax': 'Аякс',
  'AFC Ajax': 'Аякс',
  'PSV': 'ПСВ',
  'PSV Eindhoven': 'ПСВ',
  'Feyenoord': 'Фейеноорд',
  'AZ Alkmaar': 'АЗ',
  'AZ': 'АЗ',
  'Utrecht': 'Утрехт',
  'FC Utrecht': 'Утрехт',
  'Twente': 'Твенте',
  'FC Twente': 'Твенте',

  // Portugal
  'Benfica': 'Бенфика',
  'SL Benfica': 'Бенфика',
  'Porto': 'Порту',
  'FC Porto': 'Порту',
  'Sporting CP': 'Спортинг',
  'Sporting': 'Спортинг',
  'Braga': 'Брага',
  'SC Braga': 'Брага',

  // Scotland
  'Celtic': 'Селтик',
  'Rangers': 'Рейнджерс',

  // Turkey
  'Galatasaray': 'Галатасарай',
  'Fenerbahce': 'Фенербахче',
  'Fenerbahçe': 'Фенербахче',
  'Besiktas': 'Бешикташ',
  'Beşiktaş': 'Бешикташ',
  'Trabzonspor': 'Трабзонспор',

  // Russia — RPL
  'Zenit': 'Зенит',
  'Zenit St Petersburg': 'Зенит',
  'CSKA Moscow': 'ЦСКА',
  'PFC CSKA Moscow': 'ЦСКА',
  'Spartak Moscow': 'Спартак',
  'Lokomotiv Moscow': 'Локомотив',
  'Dinamo Moscow': 'Динамо',
  'FK Dynamo Moscow': 'Динамо',
  'Krasnodar': 'Краснодар',
  'FK Krasnodar': 'Краснодар',
  'Rubin Kazan': 'Рубин',
  'Rostov': 'Ростов',
  'FK Rostov': 'Ростов',
  'Akhmat Grozny': 'Ахмат',
  'Sochi': 'Сочи',
  'FK Sochi': 'Сочи',
  'Khimki': 'Химки',
  'FK Khimki': 'Химки',
  'Ural': 'Урал',
  'FK Ural': 'Урал',
  'Krylya Sovetov': 'Крылья Советов',
  'Samara': 'Крылья Советов',
  'Fakel Voronezh': 'Факел',
  'Orenburg': 'Оренбург',
  'FK Orenburg': 'Оренбург',
  'Nizhny Novgorod': 'Нижний Новгород',
  'FK Nizhny Novgorod': 'Нижний Новгород',
  'Pari Nizhny Novgorod': 'Нижний Новгород',
  'Torpedo Moscow': 'Торпедо',

  // Brazil
  'Flamengo': 'Фламенго',
  'CR Flamengo': 'Фламенго',
  'Fluminense': 'Флуминенсе',
  'Palmeiras': 'Палмейрас',
  'SE Palmeiras': 'Палмейрас',
  'Corinthians': 'Коринтианс',
  'Santos': 'Сантос',
  'FC Santos': 'Сантос',
  'Gremio': 'Гремио',
  'Grêmio': 'Гремио',
  'Internacional': 'Интернасьонал',
  'Sport Club Internacional': 'Интернасьонал',
  'Atletico Mineiro': 'Атлетико Минейро',
  'Atlético Mineiro': 'Атлетико Минейро',
  'Botafogo': 'Ботафого',
  'Sao Paulo': 'Сан-Паулу',
  'São Paulo': 'Сан-Паулу',
  'Vasco da Gama': 'Васко да Гама',
  'Cruzeiro': 'Крузейро',
  'Fortaleza': 'Форталеза',
  'Bahia': 'Баия',
  'Bragantino': 'Брагантино',
  'Red Bull Bragantino': 'Брагантино',

  // Argentina
  'Boca Juniors': 'Бока Хуниорс',
  'River Plate': 'Ривер Плейт',
  'Racing Club': 'Расинг',
  'Independiente': 'Индепендьенте',
  'San Lorenzo': 'Сан-Лоренсо',
  'Estudiantes': 'Эстудьянтес',
  'Lanus': 'Ланус',
  'Newells Old Boys': 'Ньюэллс',
  "Talleres": 'Тальерес',

  // USA / MLS
  'Inter Miami': 'Интер Майами',
  'Inter Miami CF': 'Интер Майами',
  'LA Galaxy': 'ЛА Гэлакси',
  'LAFC': 'LAFC',
  'Los Angeles FC': 'LAFC',
  'New York City FC': 'Нью-Йорк Сити',
  'New York Red Bulls': 'Нью-Йорк Ред Буллз',
  'Seattle Sounders': 'Сиэтл Саундерс',
  'Atlanta United': 'Атланта Юнайтед',
  'Portland Timbers': 'Портленд Тимберс',
  'CF Montreal': 'Монреаль',
  'Toronto FC': 'Торонто',
  'Columbus Crew': 'Коламбус',
  'Charlotte FC': 'Шарлотт',
  'St. Louis City': 'Сент-Луис',
  'Philadelphia Union': 'Филадельфия',
  'DC United': 'Ди Си Юнайтед',

  // Champions League regulars
  'Borussia Dortmund': 'Боруссия Дортмунд',
  'Porto': 'Порту',
  'Shakhtar Donetsk': 'Шахтёр',
  'Shakhtar': 'Шахтёр',
  'Dynamo Kyiv': 'Динамо Киев',
  'Dinamo Zagreb': 'Динамо Загреб',
  'GNK Dinamo': 'Динамо Загреб',
  'Red Bull Salzburg': 'Зальцбург',
  'FC Red Bull Salzburg': 'Зальцбург',
  'Salzburg': 'Зальцбург',
  'Club Brugge': 'Брюгге',
  'Club Brugge KV': 'Брюгге',
  'Anderlecht': 'Андерлехт',
  'RSC Anderlecht': 'Андерлехт',
  'Young Boys': 'Янг Бойз',
  'BSC Young Boys': 'Янг Бойз',
  'Viktoria Plzen': 'Виктория Пльзень',
  'Slavia Prague': 'Славия Прага',
  'SK Slavia Prague': 'Славия Прага',
  'Sparta Prague': 'Спарта Прага',
  'AC Sparta Prague': 'Спарта Прага',
  'Benfica': 'Бенфика',
  'Bruges': 'Брюгге',
  'Legia Warsaw': 'Легия',
  'Legia': 'Легия',

  // Misc Europe
  'Olympiacos': 'Олимпиакос',
  'PAOK': 'ПАОК',
  'AEK Athens': 'АЕК',
  'Hajduk Split': 'Хайдук',
  'Panathinaikos': 'Панатинаикос',
  'Anderlecht': 'Андерлехт',
  'Genk': 'Генк',
  'KRC Genk': 'Генк',
  'Gent': 'Гент',
  'KAA Gent': 'Гент',
  'Standard Liege': 'Стандард',
  'Standard Liège': 'Стандард',
  'Lech Poznan': 'Лех',
  'Wisla Krakow': 'Вислa',
  'Maccabi Tel Aviv': 'Маккаби ТА',
  'Maccabi Haifa': 'Маккаби Хайфа',
  'Ferencvaros': 'Ференцварош',
  'Ferencváros': 'Ференцварош',
}

// Normalize key for lookup (handle slight variations)
function normalizeKey(name) {
  return (name || '').trim().replace(/\s+/g, ' ')
}

export function translateTeam(name) {
  if (!name) return name
  const key = normalizeKey(name)
  return TEAM_NAMES_RU[key] || name
}
